content/docs/hello-world.md
=> Translation of the Hello World page

GLOSSARY.md
=> Added `tag` to Untranslatable terms

GLOSSARY.md
Added a reference to issue #108 to the Glossary
=> Added ref to #108 (Translating "mount" and "unmount" in sentences)

content/docs/composition-vs-inheritance.md, content/docs/nav.yml, examples/composition-vs-inheritance/1.css, examples/composition-vs-inheritance/1.js, examples/composition-vs-inheritance/2.css, examples/composition-vs-inheritance/2.js, examples/composition-vs-inheritance/3.css, examples/composition-vs-inheritance/3.js, examples/composition-vs-inheritance/4.css, examples/composition-vs-inheritance/4.js
Closes #25 , Replaces #111 
used CodeSandox as it's happening upstream:
https://github.com/reactjs/reactjs.org/pull/913
...which allows uploading CSS (currently we can't with CodePen)
=> Translation of the Page: `Composition vs Inheritance`

content/docs/code-splitting.md, content/languages.yml, content/tutorial/tutorial.md
It looks like that #120 was merged with squash merge, the bot tried to merge the conflicts in #123 but the commit `fc7f60f2bd1c304f0122f5fd09b8256e7d563f1c` created by it was targeting a different source.
Here's what I did to fix:
- Reverted squash merge from #120
- Applied the changeset from **Sync with reactjs.org @ 8803c63** again
- Applied the changeset from **Sync with reactjs.org @ b50fe64c** by merging b50fe64c manually
Result: Both syncs have been applied so we are tracking b50fe64c correctly.
As you can see in the screenshot from upstream, it matches with the changes below:
Replaces #123 so it can be closed
=> Fixing sync with upstream

content/home/marketing/component-based.md, content/home/marketing/declarative.md, content/home/marketing/learn-once-write-anywhere.md, src/pages/index.js
~~Maybe @MicheleBertoli can review this :o)~~ nvm it seems that actual italian speakers review these PRs :)
=> Home page tweaks/rephrasing

src/components/LayoutHeader/DocSearch.js
Updating apiKey for the Italian website
Ref: #135
=> DocSearch: apikey

content/community/conferences.md, content/docs/add-react-to-a-website.md
=> Translation for the page 'Add React to a Website'

content/docs/hooks-overview.md
=> feat(hooks-overview): Translation to Italian

content/docs/hooks-state.md
=> Feature(hooks-state): Italian translation

content/docs/forms.md
=> Fixed translation forms.md

content/docs/hooks-custom.md
=> Feature(hooks-custom): Italian translation

content/docs/components-and-props.md
Closes #196
Credits to @riccardodicurti
=> fix(typo): semprare

content/docs/rendering-elements.md
Hi All,
I am studying React with your tutorial and correct errors in the Italian (my mother tongue)Version.
Please verify and approve my pull request.
Paola
=> mis-typing and translation inconsistency

content/docs/reference-events.md
=> Corrected some typos

content/docs/forms.md
=> A translation of the coconut value was missing

content/docs/hooks-overview.md
=> Fixed typo (from setCount to setContatore)

content/docs/reference-react-component.md
First one: `discentente  ~> discendente ` 
Second one: `ritardardare  ~> ritardare `
=> Fix 2 typos

content/docs/components-and-props.md
=> Correction of "punto" instead "pundo"

content/warnings/invalid-aria-prop.md
=> Add translation for invalid-aria-prop warning

content/docs/getting-started.md
The Italian version of https://developer.mozilla.org/en-US/docs/Web/JavaScript/A_re-introduction_to_JavaScript does not exist
=> fixed link

content/docs/faq-structure.md
=> Translate 'FAQ -> File Structure' in Italian

content/docs/forwarding-refs.md
=> Forwarding refs translation

src/site-constants.js
=> style(site-constants): fixed linting error

content/docs/components-and-props.md
=> error in line 74

src/content/learn/your-first-component.md, src/sidebarLearn.json
Added translations for `your-first-component`.
See https://github.com/reactjs/it.react.dev/issues/418
=> Translate "Your first component"

src/content/learn/javascript-in-jsx-with-curly-braces.md, src/sidebarLearn.json
JavaScript in JSX with Curly Braces translation
=> JavaScript in JSX with Curly Braces translation

src/content/learn/index.md
```
Otterrai due cose da `useState`: lo state attuale (`count`) e la funzione ti consente di aggiornarlo (`setCount`).
```
```
Otterrai due cose da `useState`: lo state attuale (`count`) e la funzione che ti consente di aggiornarlo (`setCount`).
```
=> fix(learn/index): add missing conjunction to sentence

src/content/learn/responding-to-events.md, src/sidebarLearn.json
Translation for _"Responding to Events"_ page and its related sidebar label
Ref https://github.com/reactjs/it.react.dev/issues/418
=> Translated "Responding to Events" page & related sidebar label

src/components/MDX/ExpandableCallout.tsx, src/components/MDX/ExpandableExample.tsx, src/content/learn/conditional-rendering.md, src/sidebarLearn.json
Translation for _"Conditional Rendering"_ page.
Also added <ExpandableCollout> and <ExpandableExample> components translations.
Ref https://github.com/reactjs/it.react.dev/issues/418
=> Translated "Conditional Rendering" && Expandable Collout

src/content/learn/render-and-commit.md, src/sidebarLearn.json
Italian translation for "Render and commit" page and sidebar entry.
Part of https://github.com/reactjs/it.react.dev/issues/418
=> Translated Render and commit

src/components/Layout/Page.tsx, src/components/Layout/TopNav/TopNav.tsx, src/content/learn/start-a-new-react-project.md, src/content/learn/tutorial-tic-tac-toe.md
- Fix conflicts from the latest sync
- Adapt documentation with latest version
=> fix: conflicts

src/content/learn/extracting-state-logic-into-a-reducer.md, src/content/reference/react/useReducer.md, src/sidebarLearn.json
Partially address #418 
Translation of page content.
Translation of page title in sidebarLearn.json.
Translation of page title in useReducer.md
=> docs: extracting state logic into a reducer
