content/home/examples/a-component-using-external-plugins.js
content/home/examples/a-component-using-external-plugins.md
content/home/examples/a-simple-component.js
content/home/examples/a-simple-component.md
content/home/examples/a-stateful-component.js
content/home/examples/a-stateful-component.md
content/home/examples/an-application.js
content/home/examples/an-application.md
content/home/marketing/component-based.md
content/home/marketing/declarative.md
content/home/marketing/learn-once-write-anywhere.md
src/pages/index.js

Home Page Translation

---

GLOSSARY.md
README.md
STYLE_GUIDE.md

This is just to tidy up things a bit.
@LucaBlackDragon: would you mind adding the content of the pinned style guide issue inside the file below and updating the issue with a link to the file?
Obviously only if you agree with this small refactoring.
I believe we should keep Glossary and Style guide in source control to track their changes, pinned issues are cool but they are not git! 😄

housekeeping: Adjusted README, versioned Glossary + Style Guide

---

content/docs/nav.yml
content/docs/rendering-elements.md
content/docs/state-and-lifecycle.md

Translation of the `Rendering Elements` page

---

GLOSSARY.md
content/docs/handling-events.md
content/docs/nav.yml

Translation for the page 'Handling Events'

---

content/docs/handling-events.md
examples/handling-events/1.js

Using CodeSandbox as it is happening upstream (see https://github.com/reactjs/reactjs.org/pull/913).

Move code samples in "Handling Events"

---

.gitignore
GLOSSARY.md
content/docs/forms.md
examples/forms/1.js
examples/forms/2.js
examples/forms/3.js

Translation for the page 'Basics -> Forms'

---

content/community/conferences.md
content/docs/reference-react-dom.md

Ciao.
This is the translation for ReactDOM API reference.

Add translation for ReactDOM API reference

---

content/docs/nav.yml
content/docs/reference-dom-elements.md

Translation for the page 'API Reference -> DOM Elements'

---

GLOSSARY.md
content/community/conferences.md
content/docs/code-splitting.md
content/docs/codebase-overview.md
content/docs/error-boundaries.md
content/docs/nav.yml
content/docs/react-without-es6.md
content/docs/reference-react-component.md
content/docs/reference-react.md
examples/react-component-reference/get-snapshot-before-update.js

Translation for the page 'React.Component'

---

content/blog/2017-09-26-react-v16.0.md
content/docs/nav.yml
content/docs/reference-javascript-environment-requirements.md

Translation for the page 'API Reference -> JS Environment Requirements'

---

content/docs/addons-shallow-renderer.md
content/docs/nav.yml

Translation for the page 'API Reference -> Shallow Renderer'

---

content/docs/addons-test-utils.md
content/docs/hooks-faq.md

Add translation for API Reference > Test Utilities

---

content/docs/reference-events.md

Translation for the page 'API Reference -> SyntheticEvent' (#31)

Translation for the page 'API Reference -> SyntheticEvent' (#31)

---

content/docs/getting-started.md
static/html/single-file-example.html

Translation for the page 'Installation -> Getting Started'

---

content/docs/conditional-rendering.md

"comportamnento" to "comportamento"

Syntax error

---

content/docs/state-and-lifecycle.md

There's a couple of comments in code examples which are not translated in Italian, while other comments are.
I just fixed those translations using same comments used as translations in other code examples.

Fix missing translations in state-and-lifecycle.md

---

content/docs/conditional-rendering.md

While reading the documentation i noticed this small syntax error on an external link.
Greetings 😃

Fix for a small syntax error of a link

---

content/docs/fragments.md

Italian translation of the page

---

content/docs/reconciliation.md

Ciao, I finished the issue #71 .
On the _"Chiavi"_ paragraph, I chose to keep using `key` instead of translating it as 'chiave' because, in my opinion, it is more clear for the user that _we are specifically referring to the prop itself_, not only the concept. Let me know if it is ok for you to keep using 'key'. If that is the case, maybe we could consider to add it in the [Glossary](https://github.com/reactjs/it.reactjs.org/blob/master/GLOSSARY.md). Let me know if I should fix something on the translation or on the sentences and I will do it asap 😄 👍

Translate Reconciliation 

---

content/docs/error-boundaries.md

Error boundaries translation

---

beta/src/pages/learn/editor-setup.md
beta/src/pages/learn/installation.md
beta/src/pages/learn/start-a-new-react-project.md

This PR adds translations for the following pages: 
-  Installation (note: a lot of content here is similar to old website)
- Start a New React Project
- Editor Setup
in new BETA website

Beta website part I

---

src/content/learn/react-developer-tools.md

Translation for **React Developer Tools** page in Beta website (now live)
Part of #328

Beta website: translate React Developer Tools

---

src/components/MDX/MDXComponents.tsx
src/content/learn/installation.md
src/sidebarLearn.json

Added translations for _"Installation"_ page and updated translations for the _"In this chapter"_ code block.
See [#418](https://github.com/reactjs/it.react.dev/issues/418)

Translated "Installation" page & "In this chapter" block's label

---

src/components/Layout/Footer.tsx
src/content/blog/2023/03/16/introducing-react-dev.md
src/content/learn/index.md
src/content/learn/thinking-in-react.md
src/sidebarHome.json
src/sidebarLearn.json

Translate **Quick Start** page
Part of #418

Translate "Quick Start" page

---

src/content/learn/writing-markup-with-jsx.md
src/sidebarLearn.json

Italian translation for "Writing markup with jsx" page and sidebar entry.
(I'm newbie, not sure if i did all alright.)
Part of https://github.com/reactjs/it.react.dev/issues/418

Translate "Writing markup with jsx" page

---

src/components/Layout/Toc.tsx
src/content/learn/add-react-to-an-existing-project.md
src/sidebarLearn.json

Translation for _"Add React to an existing project"_ page and sidebar entry.
Also added a fix for TOC's heading.
Ref #418

Translated "Add React to an existing project" page content; fixed TOC's heading & sidebar

---

src/content/learn/describing-the-ui.md
src/sidebarLearn.json

Italian translation for "Describing the UI" page and sidebar entry.
Part of https://github.com/reactjs/it.react.dev/issues/418

Translated Describing the UI

---

src/components/MDX/Challenges/Challenge.tsx
src/components/MDX/Challenges/Challenges.tsx
src/components/MDX/MDXComponents.tsx
src/components/MDX/Recap.tsx
src/content/learn/passing-props-to-a-component.md
src/sidebarLearn.json
src/utils/prepareMDX.js

Translation for _"Passing props to to a component"_ page.
Also added `<Challenge>,` `<Recap>`, `<Illustration>` components translations.
Ref https://github.com/reactjs/it.react.dev/issues/418

Translated page content & Challenge, Recap, Illustration components translations

---

src/content/learn/keeping-components-pure.md
src/sidebarLearn.json

Italian translation for "Keeping components pure" page and sidebar entry.
Alcuni termini come: 
Side Effects
Story Tray
Ho preferito non tradurli, ma non so, vorrei qualche parere.
Part of https://github.com/reactjs/it.react.dev/issues/418

Translated Keeping components pure

---

src/components/MDX/Challenges/Challenges.tsx
src/content/learn/passing-props-to-a-component.md

@mattia-sanfilippo reviewed [my PR](https://github.com/reactjs/it.react.dev/pull/428) and left me some comments after it was merged: I have now addressed them so we can consider it really closed 😃
Ref: #418

Adjusted translations on "Passing props to to a component" page

---

src/content/learn/adding-interactivity.md
src/sidebarHome.json
src/sidebarLearn.json

Partially addresses #418.
- Translation of page content.
- Translation of page title in `sidebarLearn`.
- Translation of page title in `sidebarHome`.

Translate: Adding Interactivity

---

src/sidebarHome.json

Generally on desktop you won't see it, but on a smaller viewport the homepage renders `sidebarHome.json`.
Currently it's missing the translations for **Installation** and **Describing the UI** pages, which are instead translated in `sidebarLearn.json`
We'll have to remember this for the future 😃

translate(sidebar-home): add missing title translations

---

src/content/learn/tutorial-tic-tac-toe.md

Translate "Tutorial: Tic Tac Toe"
Part of #418

docs: translate tutorial: tic tac toe

---

src/content/learn/state-a-components-memory.md
src/sidebarLearn.json

Partially addresses https://github.com/reactjs/it.react.dev/issues/418.
- Translation of page content.
- Translation of page title in `sidebarLearn.json`.

Translate: State A Component's Memory

---

src/content/learn/updating-objects-in-state.md
src/sidebarLearn.json

Partially addresses https://github.com/reactjs/it.react.dev/issues/418.
- Translation of page content.
- Translation of page title in sidebarLearn.json.

Docs: translate "Updating Objects in State"

---

src/content/learn/importing-and-exporting-components.md
src/sidebarLearn.json

Added translations for `importing-exporting-components`.
See https://github.com/reactjs/it.react.dev/issues/418

translate importing-exporting-components

---

src/content/learn/managing-state.md
src/sidebarHome.json
src/sidebarLearn.json

Translate managing-state

---

src/content/learn/passing-data-deeply-with-context.md
src/sidebarLearn.json

Partially addresses https://github.com/reactjs/it.react.dev/issues/418.
Translation of page content.
Translation of page title in sidebarLearn.json.

docs: translate page passing data deeply with context
